// Generated by CoffeeScript 1.7.1
(function() {
  describe("Image", function() {
    it("initializes successfully", function() {
      var image;
      image = new Image([1, 2, 3], {
        slice_duration: 12
      }, 'volume');
      expect(image).toBeDefined();
      expect(image.header).toBeDefined();
      return expect(image.description).toBe('');
    });
    it("loads from a URL", function() {
      var image;
      image = Image.load('data/brain.nii.gz');
      return expect(image).toBeDefined();
    });
    it("returns the header", function() {
      var image;
      image = new Image([1, 2, 3], 'I am a header!', 'volume');
      return expect(image.getHeader()).toBe('I am a header!');
    });
    return it("returns the data", function() {
      var image;
      image = new Image('I am some data!', 14, 'volume');
      return expect(image.getData(false)).toBe('I am some data!');
    });
  });

}).call(this);
